### ISSUE TITLE
Field ti_nm is specified as an unrecognised event in Snowplow Inspector

### ISSUE THREAD

**Issue by kingo55** [poplindata/chrome-snowplow-inspector#31]
I was QA'ing some tags here and noticed the name was missing from a transaction item event.

Turns out the field was unrecognised by this inspector:

<img width="1259" alt="Screen Shot 2020-03-12 at 09 50 33" src="https://user-images.githubusercontent.com/2361388/76471787-be840480-6447-11ea-8d82-e9649c1cd22c.png">

To be fair, this is also not specified in Snowplow's tracker protocol: https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol#352-transaction-item-parameters

We're running 2.12.0 of the JS tracker here and it's pushing `ti_nm` for the field, but it's being showing up in Redshift/BigQuery here. 

Should I raise this on the Snowplow Github too?

**Comment by miike** [comment]
Thanks for raising @kingo55 

It looks like `ti_nm` and `ti_na` are both acceptable forms to the enricher but `ti_nm` was a bug that made it into all the trackers. We should be able to add this into the debugger - but not sure if it's worth adding into Snowplow as it looks like it's designed to handle both due to the bug:

https://github.com/snowplow/snowplow/commit/f52dbed167bc4ff022e1cf1927084f2134f969cd

**Comment by kingo55** [comment]
Thanks @miike!
