### ISSUE TITLE
Inspector has stopped working with old version of SDK

### ISSUE THREAD

**Issue by angiep** [poplindata/chrome-snowplow-inspector#40]
Hey there,

I am currently using an old version of the JS SDK in production (v2.4.3) and have been using this Chrome extension to test events. Last week, I noticed that this extension stopped displaying any events but confirmed that data was still being tracked. 

I noticed that a new version of this extension had been released (v0.2.16) so decided to see if I built v0.2.15 if the extension would begin working again. Luckily, v0.2.15 continues to work so I do have a work-around for now.

Let me know if there are any plans to support older versions of the SDK or if there's anymore information that I can send over to debug. At the very least, I wanted to make you aware to document.

Thanks!

**Comment by angiep** [comment]
Thanks @miike and @jethron for the fast response!

Here's a page where we are experiencing the issue: https://www.mavenclinic.com/app/maven-signup

**Comment by jethron** [comment]
Thanks for the report @angiep ! This is fixed in 7999e2622d, which re-adds support for unstruct events with non-SDJ payloads.

This is in v0.2.18, which should roll out soon, pending review from the Chrome store. The timeline will consider the events unrecognised, but the debug view will complain that the events are invalid since they don't follow the unstruct_event schema that wraps them. But they should still be viewable as usual now. Hopefully that's an OK compromise in this case.

Let us know if you have any further issues!

**Comment by angiep** [comment]
Thanks so much for quickly patching this!
