### ISSUE TITLE
Link click tracking 

### ISSUE THREAD

**Issue by misha-kotov** [poplindata/chrome-snowplow-inspector#44]
The extension works great for the most part but it does not seem to be detecting native [JS tracker link clicks](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/tracking-events/#link-click-tracking) (given link tracking is enabled) or custom link clicks fired as [structured events](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/tracking-events/#tracking-custom-structured-events). We see the events in our event pipeline but not in your extension.
Is there any guidance how to surface those in your chrome extension?

**Comment by jethron** [comment]
Thanks for your report @misha-kotov!

These should get picked up for sure.
For some brief testing we've enabled link tracking on poplindata.com and we can see the events in the extension in both Chrome and Edge.

Are you able to share a link to the site where the events are not showing up so I can investigate?

In the mean time, the classic link-tracking work around of "hold control while you click the link to open the link in a new tab" should work.

**Comment by misha-kotov** [comment]
Hi @jethron , thanks for your quick response! Let's take this site for example: https://marketplace.magento.com
We have set up link click tracking enabled and also have custom click events when user clicks on any item in the "most popular" carousel at the top (we're more interested in these). We see both types of events in ES, but not in the extension.

**Comment by jethron** [comment]
Thanks @misha-kotov, that helps.

There's a few potential issues here I think.

For the carousels on that page, these may not tracked as link clicks because the carousel is generated dynamically and added to the page via JavaScript after an API request is made. The tracker's implementation only binds tracking to links that exist on the page when the tracker processes the `enableLinkClickTracking` call, so there's probably a race condition here that determines if it is tracked as a link click or not (Race between which loads first, Snowplow or the carousel: if the carousel wins it gets tracked, otherwise it doesn't). You can fix this by having the carousel rendering code call [refreshLinkClickTracking](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/browser-tracker/browser-tracker-v3-reference/tracking-events/#refreshLinkClickTracking) once it's built the component and added it to the DOM. The carousel at the very top with brand logos for Wayfind and Paypal etc has the same problem; it would probably required a binding to its [init event](https://kenwheeler.github.io/slick/#settings) to call `refreshLinkClickTracking`, though it also has buttons (e.g. 'Get started') that are `button` elements, rather than `a` elements so they won't get picked up. The 'Most Popular' one looks in-house, though, so you should be able to just get a dev to call `refreshLinkClickTracking` when they fire the `impression-render` event or shortly thereafter.

Here's a little snippet you can run to see this more visually: When the tracker adds link tracking to a link, it sets a flag on the link so if `refreshLinkClickTracking` is called it doesn't introduce double-tracking. The flag is just a variable called the name of the tracker. Your tracker is `sp`, so you can run a snippet like this in your browser console to show the untracked links:
```javascript
[].forEach.call(document.getElementsByTagName('a'),  (e) => {
  if (e.sp !== true) {
    e.style.outlineWidth = '5px';
    e.style.outlineColor = 'red';
    e.style.outlineStyle = 'solid';
  }
})
```
This looks at every link on the page, and if it doesn't have the flag set, puts a red box around it. (Though the slick carousel doesn't work because of some funky layout stuff on the `a` elements, sorry). When the carousel doesn't load first and link tracking won't fire, you should get this: 
![image](https://user-images.githubusercontent.com/1646397/148306281-b096dc41-3f86-45a3-a21f-d22885717d49.png)
Though for some pageviews you would conceivably not get the red boxes at all and the tracking would work.

For the broader link clicks that sometimes don't appear, I think this is a problem due to the use of the [sendBeacon](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/browser-tracker/browser-tracker-v3-reference/tracker-setup/initialization-options/#Beacon_API_support) method for tracking your events. I'm observing even when a network request goes out in the browser developer tools' Network tab, the requests don't have a payload/body. They probably do have a payload in reality (the requests have a Content-Length that looks reasonable), so would show up in your pipeline, but for whatever reason the APIs the browsers gives us to examine the network request don't have access to it; so there's no event to parse and thus it doesn't show up in the extension. I'm not sure how to resolve that, it's more of an underlying browser bug I think.

I'd suggest (maybe just as a temporary experiment) changing back to the regular default `POST` method for a while and seeing if that helps. `beacon` has historical reliability issues, so you may see things start working in the extension, as well as an increase in data actually collected. I'd be interested to hear if you see any improvements or (especially) not. Link tracking is kind of the go-to use case for `beacon`, but the Snowplow tracker's localStorage queue for post requests should in theory be more reliable as long as the link isn't going to an external domain (if it can't send before the browser navigates it should get sent with the next pageview).

Hope this helps, let us know if you still see problems after those changes -- but for now I can't see that these are issues that can be fixed by the extension.

**Comment by jethron** [comment]
Closing for now as I don't think this is an issue with the extension itself.

**Comment by misha-kotov** [comment]
Wow, thank you for taking the time to write out such a detailed response, @jethron ! 
We will consider implementing your suggestions

**Comment by jethron** [comment]
Reopening this.

Since we can detect this issue when it happens (as long as not using custom paths), we should at least display in the extension that we saw a request we can't display. We can then explain that it's probably due to using `beacon` and beyond our control. The number of events in the listing would then at least be accurate(ish, we don't know how many events were in the request), even though we can't show any actual details about the event.
