### ISSUE TITLE
"Snowplow" tab does not always appear in DevTools

### ISSUE THREAD

**Issue by sharif-anatta** [poplindata/chrome-snowplow-inspector#49]
1. It does not open the snowplow in inspector at once I need to try 20-30 times to load the snowplow.

**Comment by jethron** [comment]
Hey @sharif-anatta,

Thanks for your feedback, I'm really sorry you haven't had a good experience with the extension.

If the events aren't displaying for you quickly this is probably a bug and we would very much like to fix that bug for you and any others experiencing the issue.

If it's public, would you be able to share with us the URL of the page you are trying to view Snowplow events on, so I can try and see what might be causing the unreliability you're seeing? Then we can hopefully resolve the issue and get the extension working as reliably as you would expect.

Thankyou for your time reporting this issue, hopefully we are able to fix the situation quickly.

**Comment by pwm1991** [comment]
Don't agree with the hyperbole but the extension rarely loads on charlottetilbury.com or our dev sites on the first try.

My solution is to visit snowplowanalytics.com, get the extension to load there, then visit the domain i need to test.

**Comment by jethron** [comment]
Thanks @pwm1991 for the example site, that's very helpful!

Unfortunately I'm not able to replicate the issue. :sweat_smile:

If I:

1. Go to `charlottetilbury.com`, get redirected to https://www.charlottetilbury.com/au
2. Right click, Inspect Element to open DevTools, hit the Snowplow tab
3. See no events (per the [DevTools documentation](https://developer.chrome.com/docs/extensions/reference/devtools_network/), 
    > If the Developer Tools window is opened after the page is loaded, some requests may be missing in the array of entries returned by getHAR(). Reload the page to get all requests. In general, the list of requests returned by getHAR() should match that displayed in the Network panel.

    )
4. Switch to the Network tab to verify no events have been sent since DevTools was opened (filter: `trk. -method:OPTIONS`)
5. Hit `Ctrl + R` to refresh the page (or just wait a while for the next `csm.view` or make a `csm.hover` event fire)
6. See the expected events (on refresh: 1 pageview, a few self describing events) fire in the Network tab and correspondingly appear in the extension

When you say it "barely loads", do you mean "no events appear on the left" or "the extension UI does not appear"?

**Comment by jethron** [comment]
Someone pointed out that this might actually be in reference to the tab itself (not) appearing in DevTools? Rather than the extension (not) working as expected once loaded as I went through above.

Is that the actual issue you're seeing @sharif-anatta / @pwm1991 ?

**Comment by pwm1991** [comment]
Rarely not barely :) Yep, 100% It's the extension tab not loading. The extension is working otherwise.

Let me be clear:

When I visit charlottetilbury.com and accept all cookies
Snowplow SDK loads
When I open DevTools
Snowplow extension tab is not present

To resolve I:

Visit snowplowanalytics.com
Open DevTools
Snowplow extension tab is present (and populating)

Then, when I visit ct.com, the Snowplow extension tab is present and populating.

**Comment by jethron** [comment]
> Rarely not barely :)

Typo, my bad. :sweat_smile:

Thanks for the detail & clarification on this @pwm1991, very helpful.

This does unfortunately look to be a Chrome bug of some sort, (existing patch at least!) so unfortunately all we can do is wait. :frowning_face: We seem to be in good company though:
- https://github.com/facebook/react/issues/24094
- https://bugs.chromium.org/p/chromium/issues/detail?id=1305475
- https://bugs.chromium.org/p/chromium/issues/detail?id=1313542
- https://bugs.chromium.org/p/chromium/issues/detail?id=1316642
- https://bugs.chromium.org/p/chromium/issues/detail?id=1315534
- https://bugs.chromium.org/p/chromium/issues/detail?id=1316642
- https://bugs.chromium.org/p/chromium/issues/detail?id=1306249

**Comment by jethron** [comment]
Per https://bugs.chromium.org/p/chromium/issues/detail?id=1305475#c19 this should be fixed in Chrome 102.

**Comment by miike** [comment]
Closing - Chrome has now fixed this issue (in 102/103).
