### ISSUE TITLE
Feature request - customize display of events

### ISSUE THREAD

**Issue by richard-ling** [poplindata/chrome-snowplow-inspector#53]
I'd like to customize how events are displayed, so that it displays what's important to me.

It's mildly annoying that the top third of the my display is taken up with fields I don't need to read, in an excessively large font. There seems no way to collapse this top section, so maybe adding that would be a quick win. Even nicer if I can turn off fields I don't care about.

The other issue I have is that my structured events' `se_pr` field is a stringified JSON object, and it would be much easier to read if there was a way to parse it and show the object instead of the string.

I figured I might be able to solve both problems with a custom schema. But can't work out how to make a local schema that overrides the one specified in the event. So that would also be really useful. I have no idea whether a custom schema will let me parse the `se_pr` field into separate fields though.

**Comment by miike** [comment]
Thanks @richard-ling 

>It's mildly annoying that the top third of the my display is taken up with fields I don't need to read, in an excessively large font. There seems no way to collapse this top section, so maybe adding that would be a quick win. Even nicer if I can turn off fields I don't care about.

This is something we've thought about and are taking into account as part of our UI refactor (which changes the underlying framework). That refactor is still a little way off before it's finished so I'll investigate the effort involved in being able to not render fields. At the moment you can collapse groups of fields (e.g., page, browser) - is there a certain set of fields you are only interested in? (in which case we'd need to consider a per field toggle rather than a group toggle)

>I figured I might be able to solve both problems with a custom schema.

I think the best solution here is to use a self-describing event (either as an entity or event) for tracking which is designed to accept JSON rather than `se_pr`.

>But can't work out how to make a local schema that overrides the one specified in the event. So that would also be really useful. I have no idea whether a custom schema will let me parse the se_pr field into separate fields though.

At the moment we don't do any transformation of events in terms of mutating fields (beyond decoding them) so this would need to come in as self-describing JSON in order to get decoded. You can override (or add) the schemas that are used for validation in the 'Schemas' sub menu but this doesn't impact the decoding process - just what schema is used to validate against the instance.

**Comment by richard-ling** [comment]
Thanks for the quick answers!  The fields I ignore are these top 5 ones in the large font....
![Screen Shot 2022-06-07 at 1 04 27 pm](https://user-images.githubusercontent.com/50315238/172287526-efafce6b-da28-4f06-9e86-43ae9406980f.png)
They're all the same in my use case anyway, except for the time which is not relevant in my situation either.  So if I could collapse those, it would be wonderful.

Anyway if you are revisiting the UI and have taken this idea into account already, then I guess you can probably close this issue and I'll just wait for the updated UI.  Thanks.

**Comment by miike** [comment]
@jethron Is it easy for us to wrap these components in a `RowSet` (or similar) or should we defer until the refactor?

**Comment by jethron** [comment]
Hey @richard-ling,

Thanks for your suggestions! The latest release (v0.2.22) should hopefully address these requests now:

- If you go into the extension settings there's now a checkbox to display those summary fields as a collapsible group so they take up less space if you like
- String values should now be parsed as JSON if possible to try and display them more intuitively

Let us know if you have any further feedback on these changes or notice any other issues!

**Comment by richard-ling** [comment]
Awesome!  Verified both improvements are working as stated.  The JSON parsing is brilliant!  Much appreciated!
