### ISSUE TITLE
Can't get static repo to work

### ISSUE THREAD

**Issue by awoehrl** [poplindata/chrome-snowplow-inspector#59]
Hi,

I've a static repo on Google Cloud Storage, which works as expected for Snowplow. The whole bucket has public access enabled.
However, I cannot get it to work in the extension. I tried it manually and via resolver import, but with no luck. The first time I set it up, Chrome asked for additional permissions to allow the extension to connect to the bucket location, which I accepted. I can also see that https://storage.googleapis.com/* is added to the exceptions correctly.

Do I need some specific metadata to be set on my objects? Any other ideas, why this doesn't work?

Thanks for your help!
Andreas

**Comment by jethron** [comment]
Thanks for the report @awoehrl. This should be fixed in 486fc04d466926fc0c4a7249f255bcaa24056c8e (v0.2.23) when it rolls out; it should restore the behaviour of asking for permissions correctly and that will resolve the CORS issues GCS buckets have by default; my testing with a fresh bucket works as expected in this version.

Let us know if you have any further issues!
