### ISSUE TITLE
Static repo problem

### ISSUE THREAD

**Issue by awoehrl** [poplindata/chrome-snowplow-inspector#63]
Hi,

there seems to be another problem with the static repo. I'm never able to connect even when importing from my resolver file. I've tried to debug it and from what I can grasp, I would say the extension uses the wrong path for looking up schemas.

My settings:
![image](https://user-images.githubusercontent.com/44875496/217200908-33d98103-b2ef-4742-b212-57e6b87515cd.png)

As you can see here, the extension tries to look for schemas in storage.googleapis.com/schemas instead of storage.googleapis.com/my-repo/schemas:
![image](https://user-images.githubusercontent.com/44875496/217200405-d272e7e6-2e71-4f85-a3a6-0131f63f2c5e.png)

Maybe this is of help to find the culprit?

Cheers
Andreas

**Comment by jethron** [comment]
Thanks for reporting @awoehrl, this should be fixed in the new version 0.2.26 when it rolls out.
You may still see the issue, to fix that, make sure your Base URI ends with a `/`: the extension will try to lookup schemas/schema lists relative to this base so e.g. `http://storage.googleapis.com/my-repo` + `schemas` = `http://storage.googleapis.com/schemas` but `http://storage.googleapis.com/my-repo/` + `schemas` = `http://storage.googleapis.com/my-repo/schemas` 

Fixed in c6a6c8725.

**Comment by awoehrl** [comment]
Thank you!
