### ISSUE TITLE
Read the network user ID from the response of the first non-anonymous request

### ISSUE THREAD

**Issue by matus-tomlein** [poplindata/chrome-snowplow-inspector#65]
It is a bit confusing not to see the network user id for events sent in the first request to the collector after the user gave consent for tracking – users are looking specifically at this to see if the user identification is working as expected.

Perhaps we could read the ID from the `set-cookie` header in the collector response?

Happy to contribute a PR for this if it is desirable!

**Comment by miike** [comment]
@matus-tomlein PR definitely welcome if possible, it would be good to have more folks across this! @jethron Can you work with Matus to look into this please?

**Comment by jethron** [comment]
Hey @matus-tomlein!

Great point! This should be a pretty small change; the code path is a bit awkward unfortunately so it's not in a super obvious place, but [`extractRequests()`](https://github.com/poplindata/chrome-snowplow-inspector/blob/df41a73558e6be04b509fcefdb96f36a254979a8/src/components/Debugger/Timeline.tsx#L267) is your starting place, should just be a matter of checking both the request _and_ response cookies rather than just the requests'. This is pretty deep in the guts of like the first prototype code of the extension so it needs a _lot_ of love/refactoring (baby's first typescript!), but hopefully should be pretty easy to follow if you focus there.

I think historically we were trying to reduce noise here for devices that didn't support Network User ID, because it may not be stable we didn't want to display it. Pulling from the request only achieved this, but since it'll represent what's actually processed by the pipeline from the response is a better idea, IMO. Making it obvious when it's not working properly is more useful than hiding the values when it doesn't work properly.

If we could signal if it's a valid/accepted by the client cookie (attached in request) vs just assigned by the collector (set in response) that might be useful too, but to start just showing the value properly is probably good.

We also hard-code assume the cookie is called `sp` which isn't great. We can probably infer the correct name by assuming cookies set by the Collector that match UUIDs as the value are the correct cookie, rather than looking just for a single name.

Let me know if you have any issues or want to peer/codewalk or something, we can try to figure something out considering our timezones. :)
